In [44]:
import sys
from pathlib import Path

def is_google_colab() -> bool:
    if "google.colab" in str(get_ipython()):
        return True
    return False

def clone_repository() -> None:
    !git clone https://github.com/featurestorebook/mlfs-book.git
    %cd mlfs-book

def install_dependencies() -> None:
    !pip install --upgrade uv
    !uv pip install --all-extras --system --requirement pyproject.toml

if is_google_colab():
    clone_repository()
    install_dependencies()
    root_dir = str(Path().absolute())
    print("Google Colab environment")
else:
    root_dir = Path().absolute()
    # Strip ~/notebooks/ccfraud from PYTHON_PATH if notebook started in one of these subdirectories
    if root_dir.parts[-1:] == ('airquality',):
        root_dir = Path(*root_dir.parts[:-1])
    if root_dir.parts[-1:] == ('notebooks',):
        root_dir = Path(*root_dir.parts[:-1])
    root_dir = str(root_dir) 
    print("Local environment")

# Add the root directory to the `PYTHONPATH` to use the `recsys` Python module from the notebook.
if root_dir not in sys.path:
    sys.path.append(root_dir)
print(f"Added the following directory to the PYTHONPATH: {root_dir}")
    
# Set the environment variables from the file <root_dir>/.env
# from mlfs import config
# settings = config.HopsworksSettings(_env_file=f"{root_dir}/.env")

Local environment
Added the following directory to the PYTHONPATH: /home/lukasfri/Repositories/github.com/GeorgesTohme/mlfs-book

<span style="font-width:bold; font-size: 3rem; color:#333;">- Part 02: Daily Feature Pipeline for Air Quality (aqicn.org) and weather (openmeteo)</span>

## 🗒️ This notebook is divided into the following sections:
1. Download and Parse Data
2. Feature Group Insertion


__This notebook should be scheduled to run daily__

In the book, we use a GitHub Action stored here:
[.github/workflows/air-quality-daily.yml](https://github.com/featurestorebook/mlfs-book/blob/main/.github/workflows/air-quality-daily.yml)

However, you are free to use any Python Orchestration tool to schedule this program to run daily.

### <span style='color:#ff5f27'> 📝 Imports

In [45]:
import datetime
import time
import requests
import pandas as pd
import hopsworks
from mlfs.airquality import util
from mlfs import config
import json
import os
import warnings
warnings.filterwarnings("ignore")

## <span style='color:#ff5f27'> 🌍 Get the Sensor URL, Country, City, Street names from Hopsworks </span>

__Update the values in the cell below.__

__These should be the same values as in notebook 1 - the feature backfill notebook__

In [46]:
from dotenv import load_dotenv

load_dotenv(dotenv_path=f"{root_dir}/.env", override=True)

print(f"{root_dir}/.env")

import os

/home/lukasfri/Repositories/github.com/GeorgesTohme/mlfs-book/.env

In [47]:
project = hopsworks.login(engine="python")
fs = project.get_feature_store() 
secrets = hopsworks.get_secrets_api()

# This line will fail if you have not registered the AQICN_API_KEY as a secret in Hopsworks
AQICN_API_KEY = secrets.get_secret("AQICN_API_KEY").value
city = os.getenv("AQICN_CITY")
location_str = secrets.get_secret(f"SENSOR_LOCATION_JSON_{city}").value
location = json.loads(location_str)

country=location['country']
city=location['city']
street=location['street']
aqicn_url=location['aqicn_url']
latitude=location['latitude']
longitude=location['longitude']

today = datetime.date.today()

location_str

2025-11-17 17:08:44,147 INFO: Closing external client and cleaning up certificates.
Connection closed.
2025-11-17 17:08:44,149 INFO: Initializing external client
2025-11-17 17:08:44,149 INFO: Base URL: https://c.app.hopsworks.ai:443

2025-11-17 17:08:45,435 INFO: Python Engine initialized.

Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1279130

'{"country": "sweden", "city": "\\u00d6rebro", "street": "Kungsgatan", "aqicn_url": "https://api.waqi.info/feed/A547147", "latitude": "59.1605", "longitude": "15.1254"}'

### <span style="color:#ff5f27;"> 🔮 Get references to the Feature Groups </span>

In [48]:
# Retrieve feature groups
air_quality_fg = fs.get_feature_group(
    name='air_quality',
    version=1,
)
weather_fg = fs.get_feature_group(
    name='weather',
    version=1,
)

---

## <span style='color:#ff5f27'> 🌫 Retrieve Today's Air Quality data (PM2.5) from the AQI API</span>

In [49]:
import requests
import pandas as pd

aq_today_df = util.get_pm25(aqicn_url, country, city, street, today, AQICN_API_KEY)
aq_today_df

,pm25,country,city,street,date,url
0,13.0,sweden,Örebro,Kungsgatan,2025-11-17,https://api.waqi.info/feed/A547147

In [50]:
aq_today_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   pm25     1 non-null      float32
 1   country  1 non-null      object
 2   city     1 non-null      object
 3   street   1 non-null      object
 4   date     1 non-null      datetime64[ns]
 5   url      1 non-null      object
dtypes: datetime64[ns](1), float32(1), object(4)
memory usage: 176.0+ bytes

## <span style='color:#ff5f27'> 🌦 Get Weather Forecast data</span>

In [51]:
hourly_df = util.get_hourly_weather_forecast(city, latitude, longitude)
hourly_df = hourly_df.set_index('date')

# We will only make 1 daily prediction, so we will replace the hourly forecasts with a single daily forecast
# We only want the daily weather data, so only get weather at 12:00
daily_df = hourly_df.between_time('11:59', '12:01')
daily_df = daily_df.reset_index()
daily_df['date'] = pd.to_datetime(daily_df['date']).dt.date
daily_df['date'] = pd.to_datetime(daily_df['date'])
daily_df['city'] = city
daily_df

Coordinates 59.25°N 15.25°E
Elevation 38.0 m asl
Timezone None None
Timezone difference to GMT+0 0 s

,date,temperature_2m_mean,precipitation_sum,wind_speed_10m_max,wind_direction_10m_dominant,city
0,2025-11-17,-0.55,0.0,5.495161,301.607452,Örebro
1,2025-11-18,-0.80,0.0,2.811690,219.805527,Örebro
2,2025-11-19,-2.50,0.7,9.983106,25.640957,Örebro
3,2025-11-20,-2.05,0.0,16.965895,17.281584,Örebro
4,2025-11-21,-5.60,0.0,5.904439,232.431335,Örebro
5,2025-11-22,2.75,0.0,16.039202,225.909286,Örebro
6,2025-11-23,-0.10,0.0,12.101570,59.620956,Örebro

In [52]:
daily_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         7 non-null      datetime64[ns]
 1   temperature_2m_mean          7 non-null      float32
 2   precipitation_sum            7 non-null      float32
 3   wind_speed_10m_max           7 non-null      float32
 4   wind_direction_10m_dominant  7 non-null      float32
 5   city                         7 non-null      object
dtypes: datetime64[ns](1), float32(4), object(1)
memory usage: 356.0+ bytes

## <span style="color:#ff5f27;">⬆️ Uploading new data to the Feature Store</span>

In [53]:
# Insert new data
air_quality_fg.insert(aq_today_df)

2025-11-17 17:08:49,218 INFO: 	1 expectation(s) included in expectation_suite.
Validation succeeded.
Validation Report saved successfully, explore a summary at https://c.app.hopsworks.ai:443/p/1279130/fs/1265739/fg/1595960

Uploading Dataframe: 100.00% |██████████| Rows 1/1 | Elapsed Time: 00:00 | Remaining Time: 00:00

(Job('air_quality_1_offline_fg_materialization', 'SPARK'),
 {
   "success": true,
   "results": [
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "pm25",
           "min_value": -0.1,
           "max_value": 500.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 733217
         }
       },
       "result": {
         "observed_value": 12.999999046325684,
         "element_count": 1,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-17T04:08:49.000218Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     }
   ],
   "evaluation_parameters": {},
   "statistics": {
     "evaluated_expectations": 1,
     "successful_expectations": 1,
     "unsuccessful_expectations": 0,
     "success_percent": 100.0
   },
   "meta": {
     "great_expectations_version": "0.18.12",
     "expectation_suite_name": "aq_expectation_suite",
     "run_id": {
       "run_name": null,
       "run_time": "2025-11-17T17:08:49.218561+01:00"
     },
     "batch_kwargs": {
       "ge_batch_id": "b3e3cc02-c3cf-11f0-9827-581122c172fc"
     },
     "batch_markers": {},
     "batch_parameters": {},
     "validation_time": "20251117T160849.218524Z",
     "expectation_suite_meta": {
       "great_expectations_version": "0.18.12"
     }
   }
 })

In [54]:
# Insert new data
weather_fg.insert(daily_df, wait=True)

2025-11-17 17:08:56,255 INFO: 	2 expectation(s) included in expectation_suite.
Validation succeeded.
Validation Report saved successfully, explore a summary at https://c.app.hopsworks.ai:443/p/1279130/fs/1265739/fg/1595961

Uploading Dataframe: 100.00% |██████████| Rows 7/7 | Elapsed Time: 00:01 | Remaining Time: 00:00

(Job('weather_1_offline_fg_materialization', 'SPARK'),
 {
   "success": true,
   "results": [
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "wind_speed_10m_max",
           "min_value": -0.1,
           "max_value": 1000.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 733219
         }
       },
       "result": {
         "observed_value": 2.811689853668213,
         "element_count": 7,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-17T04:08:56.000255Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     },
     {
       "success": true,
       "expectation_config": {
         "expectation_type": "expect_column_min_to_be_between",
         "kwargs": {
           "column": "precipitation_sum",
           "min_value": -0.1,
           "max_value": 1000.0,
           "strict_min": true
         },
         "meta": {
           "expectationId": 733218
         }
       },
       "result": {
         "observed_value": 0.0,
         "element_count": 7,
         "missing_count": null,
         "missing_percent": null
       },
       "meta": {
         "ingestionResult": "INGESTED",
         "validationTime": "2025-11-17T04:08:56.000255Z"
       },
       "exception_info": {
         "raised_exception": false,
         "exception_message": null,
         "exception_traceback": null
       }
     }
   ],
   "evaluation_parameters": {},
   "statistics": {
     "evaluated_expectations": 2,
     "successful_expectations": 2,
     "unsuccessful_expectations": 0,
     "success_percent": 100.0
   },
   "meta": {
     "great_expectations_version": "0.18.12",
     "expectation_suite_name": "weather_expectation_suite",
     "run_id": {
       "run_name": null,
       "run_time": "2025-11-17T17:08:56.255368+01:00"
     },
     "batch_kwargs": {
       "ge_batch_id": "b8158806-c3cf-11f0-9827-581122c172fc"
     },
     "batch_markers": {},
     "batch_parameters": {},
     "validation_time": "20251117T160856.255334Z",
     "expectation_suite_meta": {
       "great_expectations_version": "0.18.12"
     }
   }
 })

%5|1763395942.916|REQTMOUT|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Timed out MetadataRequest in flight (after 60057ms, timeout #0)
%4|1763395942.916|REQTMOUT|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1763395942.916|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: 1 request(s) timed out: disconnect (after 308531ms in state UP)
%5|1763395943.240|REQTMOUT|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Timed out MetadataRequest in flight (after 60044ms, timeout #0)
%4|1763395943.240|REQTMOUT|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1763395943.240|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: 1 request(s) timed out: disconnect (after 291527ms in state UP)
%6|1763395994.349|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50000ms in state UP, 1 identical error(s) suppressed)
%6|1763395994.467|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 50110ms in state UP)
%6|1763395994.801|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50112ms in state UP)
%6|1763396045.449|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50114ms in state UP, 1 identical error(s) suppressed)
%6|1763396096.412|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 50107ms in state UP, 1 identical error(s) suppressed)
%6|1763396147.443|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50110ms in state UP, 1 identical error(s) suppressed)
%6|1763396232.972|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 84645ms in state UP, 1 identical error(s) suppressed)
%5|1763396243.254|REQTMOUT|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator/2: Timed out MetadataRequest in flight (after 60058ms, timeout #0)
%4|1763396243.254|REQTMOUT|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator/2: Timed out 1 in-flight, 0 retry-queued, 0 out-queue, 0 partially-sent requests
%3|1763396243.254|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: 1 request(s) timed out: disconnect (after 591535ms in state UP)
%6|1763396284.397|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 50105ms in state UP, 1 identical error(s) suppressed)
%6|1763396293.713|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50000ms in state UP, 1 identical error(s) suppressed)
%6|1763396293.900|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50220ms in state UP)
%6|1763396335.456|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50116ms in state UP, 1 identical error(s) suppressed)
%6|1763396344.364|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50000ms in state UP, 1 identical error(s) suppressed)
%6|1763396344.556|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50217ms in state UP, 1 identical error(s) suppressed)
%6|1763396386.427|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50109ms in state UP, 1 identical error(s) suppressed)
%6|1763396394.663|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 100028ms in state UP, 1 identical error(s) suppressed)
%6|1763396395.079|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50105ms in state UP, 1 identical error(s) suppressed)
%6|1763396437.408|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 50107ms in state UP, 1 identical error(s) suppressed)
%6|1763396445.550|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50002ms in state UP, 1 identical error(s) suppressed)
%6|1763396445.732|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50217ms in state UP, 1 identical error(s) suppressed)
%6|1763396445.821|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50121ms in state UP, 1 identical error(s) suppressed)
%6|1763396496.377|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50213ms in state UP, 1 identical error(s) suppressed)
%6|1763396532.974|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 94633ms in state UP, 1 identical error(s) suppressed)
%6|1763396546.498|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 100188ms in state UP, 1 identical error(s) suppressed)
%6|1763396546.920|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50108ms in state UP, 1 identical error(s) suppressed)
%6|1763396584.467|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50116ms in state UP, 1 identical error(s) suppressed)
%6|1763396597.370|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50000ms in state UP, 1 identical error(s) suppressed)
%6|1763396597.550|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50208ms in state UP, 1 identical error(s) suppressed)
%6|1763396635.466|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50116ms in state UP, 1 identical error(s) suppressed)
%6|1763396647.655|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 100025ms in state UP, 1 identical error(s) suppressed)
%6|1763396648.118|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50114ms in state UP, 1 identical error(s) suppressed)
%6|1763396686.415|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 50107ms in state UP, 1 identical error(s) suppressed)
%6|1763396698.556|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 50000ms in state UP, 1 identical error(s) suppressed)
%6|1763396698.637|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50000ms in state UP, 1 identical error(s) suppressed)
%6|1763396698.752|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50210ms in state UP, 1 identical error(s) suppressed)
%6|1763396737.468|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.188:9093/bootstrap]: ssl://51.161.81.188:9093/1: Disconnected (after 50117ms in state UP, 1 identical error(s) suppressed)
%6|1763396749.219|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50001ms in state UP, 1 identical error(s) suppressed)
%6|1763396749.408|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50217ms in state UP, 1 identical error(s) suppressed)
%6|1763396800.070|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50219ms in state UP, 1 identical error(s) suppressed)
%6|1763396832.975|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.81.208:9093/bootstrap]: ssl://51.161.81.208:9093/2: Disconnected (after 94630ms in state UP, 1 identical error(s) suppressed)
%6|1763396850.184|FAIL|rdkafka#consumer-12| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 100316ms in state UP, 1 identical error(s) suppressed)
%6|1763396850.623|FAIL|rdkafka#consumer-12| [thrd:GroupCoordinator]: GroupCoordinator: 51.161.81.208:9093: Disconnected (after 50110ms in state UP, 1 identical error(s) suppressed)
%6|1763396884.477|FAIL|rdkafka#producer-11| [thrd:ssl://51.161.80.189:9093/bootstrap]: ssl://51.161.80.189:9093/0: Disconnected (after 50118ms in state UP, 1 identical error(s) suppressed)

## <span style="color:#ff5f27;">⏭️ **Next:** Part 03: Training Pipeline
 </span> 

In the following notebook you will read from a feature group and create training dataset within the feature store